### ISSUE TITLE
code blocks needed in readme.md

### ISSUE THREAD

**Issue by MITARPALGROVER** [Open-Source-Chandigarh/Heritage-Threads#12]
in readme.md under contributing section the option for copying the code is missing. 
Please assign me this issue under hacktoberfest label

**Comment by Aiyaret-Sandhu** [comment]
please add a suitable description @MITARPALGROVER

**Comment by MITARPALGROVER** [comment]
@Aiyaret-Sandhu okk i have added now

**Comment by Aiyaret-Sandhu** [comment]
i have assigned you the issue
