### ISSUE TITLE
Improving the navbar advertisement on products page 

### ISSUE THREAD

**Issue by ChauhanGauri** [Open-Source-Chandigarh/Heritage-Threads#15]
The advertisement on navbar of cart page (product.html) is slightly too fast to be readable . I would like to modify the speed and pause the advertisement on hover by user. Please assign me this issue if it is eligible under Hacktoberfest.

**Comment by Aiyaret-Sandhu** [comment]
can you share  a screenshot of the above issue

**Comment by ChauhanGauri** [comment]
https://github.com/user-attachments/assets/cdc18f60-a9c0-437d-b825-51e35bba3603

**Comment by Aiyaret-Sandhu** [comment]
You can work on it

**Comment by ChauhanGauri** [comment]
Please add the hacktoberfest label.

**Comment by ChauhanGauri** [comment]
Please add the hacktoberfest label.
