### ISSUE TITLE
Missing Modal in Newsletter!

### ISSUE THREAD

**Issue by Paradox570Y1** [Open-Source-Chandigarh/Heritage-Threads#20]
I want to add a modal which on clicking Subscribe btn in Newsletter section will convey that  you have subscribed successfully . Please assign me this issue.

**Comment by Aiyaret-Sandhu** [comment]
why are you spamming the issues section. One issue would have been fine

**Comment by Paradox570Y1** [comment]
> why are you spamming the issues section. One issue would have been fine

Sorry, I had no such intention earlier i didn't gave any description for the issue so i wanted to add that so i sent it again with changes. Please assign me this issue.

**Comment by Aiyaret-Sandhu** [comment]
ok you can work on it
