### ISSUE TITLE
Fav Icon Missing on Pages

### ISSUE THREAD

**Issue by AngadSudan** [Open-Source-Chandigarh/Heritage-Threads#5]
Other than the Home Page, other pages doesn't have a fav icon or a Proper Title 

Search Page
![image](https://github.com/user-attachments/assets/21344420-afc0-4b0d-b967-83e9ab6b49a4)

Login Page
![image](https://github.com/user-attachments/assets/829b1ae9-b7ae-412e-8c99-c62eab8b6753)

Product Page
![image](https://github.com/user-attachments/assets/b61eebeb-d40b-4300-89b0-288616d576c4)

Possible Fixes- Change the Titles and add FAV Icons in the files where needed.

**Comment by AngadSudan** [comment]
Can you please add the hactoberfest-accepted label to it.

**Comment by Smit1610** [comment]
@AngadSudan Please assign this issue to me under hactoberfest 24
