### ISSUE TITLE
Fixing Ui & Enhancement 

### ISSUE THREAD

**Issue by aninima01** [Open-Source-Chandigarh/Heritage-Threads#8]
![Screenshot (195)](https://github.com/user-attachments/assets/3a947ad7-516b-44f6-8b75-0819cd0c77b3)

I would like to fix the alignment issues in the first and the third paragraph in the upperSectionContent.

1. Before the "Discover the...." in the first paragraph.
2. Before the "Each thread ... " in the third paragraph.

Kindly assign it to me.

**Comment by Parth-code286** [comment]
Hey Maintainer Pls assign this issue to me

**Comment by Aiyaret-Sandhu** [comment]
@aninima01 @Parth-code286  Both you here, Hacktoberfest demands quality over quantity please do meaningful contributions.
